name: Tests
on: [ pull_request ]

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.8, 3.9, 3.10.5 ]
        poetry-version: [ 1.2.0 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build And Run DB
        run: docker run --init -p 10001:10001 -t romanright/annadb:0.1.0
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Use Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install Package
        run: poetry install
      - name: Run Tests
        run: poetry run pytest